[package]
name = "slugger"
version = "0.1.0"
authors = ["Peter Lyons <pete@peterlyons.com>"]

[dependencies]
slugify = "0.1.0"
walkdir = "2.1.4"
# rsfs = "0.4.1"    # A generic filesystem with disk and in-memory implementations.
